      double precision m0(2500), theta_0(2500, 200)
     $               , m1(2500), theta_1(2500, 200)
     $               , m2(2500), theta_2(2500, 200)
     $               , theta_p(2500, 200), theta_m(2500, 200)
      
      double precision p0(200)
      
      common/CISimpFitData/ m0, theta_0
     $                    , m1, theta_1
     $                    , m2, theta_2
     $                    , theta_p, theta_m
     $                    , p0

